openapi: '3.0.1'
info:
    title: 'tasks-api'
    version: 'v1.0'
x-amazon-apigateway-request-validators:
    all:
        validateRequestBody: true
        validateRequestParameters: true
    params-only:
        validateRequestBody: false
        validateRequestParameters: true
x-amazon-apigateway-request-validator: params-only
paths:
    /hello:
        get:
            x-amazon-apigateway-request-validator: params-only
            parameters:
                - in: header
                  name: caller
                  required: true
                  schema:
                      type: string
            x-amazon-apigateway-integration:
                uri: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/LAMBDA_ARN/invocations
                responses:
                    default:
                        statusCode: '200'
                passthroughBehavior: 'when_no_match'
                httpMethod: 'POST'
                contentHandling: 'CONVERT_TO_TEXT'
                type: 'aws_proxy'
            summary: Hello
            description: Returns hello
            responses:
                200:
                    description: 'OK'
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/schemas/Hello'
                500:
                    description: 'Internal Server Error'
                    content: {}
        post:
            x-amazon-apigateway-request-validator: all
            summary: Hello
            description: POST hello
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/HelloRequest'
            responses:
                200:
                    description: 'OK'
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/schemas/Hello'
                500:
                    description: 'Internal Server Error'
                    content: {}
            x-amazon-apigateway-integration:
                uri: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/LAMBDA_ARN/invocations
                responses:
                    default:
                        statusCode: '200'
                passthroughBehavior: 'when_no_match'
                httpMethod: 'POST'
                contentHandling: 'CONVERT_TO_TEXT'
                type: 'aws_proxy'
components:
    schemas:
        Hello:
            properties:
                statusCode:
                    type: integer
                body:
                    type: string
        HelloRequest:
            properties:
                caller:
                    type: string
