version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "apjsb-serverless-template"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1x8ljeybgnxug"
s3_prefix = "apjsb-serverless-template"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
